name: Dev Build and Test

on:
  push:
    branches:
      - "development"

  # allow for manual runs
  workflow_dispatch:

defaults:
  run:
    shell: pwsh

env:
  BUILD_NUSPEC_PATH: PSPowerBITools-dev.nuspec
  TEST_RESULT_DIRECTORY: testresults

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.REPO_TOKEN }}

      - name: Install and cache PowerShell modules
        uses: potatoqualitee/psmodulecache@v5.1
        with:
          modules-to-cache: PSFramework

      - name: Run unit tests
        id: unit-tests
        run: |
          # Setup the parameters
          $ErrorActionPreference = "Continue"
          $params = @{
          OutputTestResult = $true
          TestResultDirectory = "$($env:GITHUB_WORKSPACE)/testresults"
          ErrorAction = "Continue"
          FailOnStderr = $false
          IgnoreLASTEXITCODE = $true
          TestGeneral = $true
          TestFunctions = $true
          }
          # Run the script
          .\tests\pester.ps1 @params

      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: "testresults/TEST-*.xml"

